---

- name: "Installing supervisor"
  homebrew:
    name: supervisor
    state: latest

- name: "Resolving supervisord path"
  shell: "echo $(brew --prefix supervisor)/bin/supervisord"
  register: supervisord_path_output

- name: "Resolving supervisorctl path"
  shell: "echo $(brew --prefix supervisor)/bin/supervisorctl"
  register: supervisorctl_path_output

- name: "Register supervisord_path fact"
  set_fact: supervisord_path="{{ supervisord_path_output.stdout }}"

- name: "Register supervisorctl_path fact"
  set_fact: supervisorctl_path="{{ supervisorctl_path_output.stdout }}"

- name: "Ensure supctl wrapper"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/supctl"
    content: |
      #!/bin/sh
      exec supervisorctl -c {{ brew_install_path }}/etc/supervisord.ini $@

- name: "Ensure supstart script (Darwin)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/supstart"
    content: |
      #!/bin/sh
      echo "Starting supervisor..."
      sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist
  when: ansible_system == "Darwin"

- name: "Ensure supstop script (Darwin)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/supstop"
    content: |
      #!/bin/sh
      echo "Stopping supervisor..."
      sudo launchctl unload -w /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist > /dev/null 2>&1
  when: ansible_system == "Darwin"

- name: "Ensure suprestart script (Darwin)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/suprestart"
    content: |
      #!/bin/sh
      echo "Stopping supervisor..."
      sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist > /dev/null 2>&1
      sleep 5
      echo "Starting supervisor..."
      sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist
  when: ansible_system == "Darwin"

- name: "Ensure supstart script (Linux)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/supstart"
    content: |
      #!/bin/sh
      sudo systemctl enable supervisord-devbrew
      sudo systemctl start supervisord-devbrew
  when: ansible_system == "Linux"

- name: "Ensure supstop script (Linux)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/supstop"
    content: |
      #!/bin/sh
      sudo systemctl stop supervisord-devbrew
      sudo systemctl disable supervisord-devbrew
  when: ansible_system == "Linux"

- name: "Ensure suprestart script (Linux)"
  copy:
    mode: 0755
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    dest: "{{ brew_brew_bin_path }}/suprestart"
    content: |
      #!/bin/sh
      sudo systemctl stop supervisord-devbrew
      sudo systemctl enable supervisord-devbrew
      sudo systemctl start supervisord-devbrew
  when: ansible_system == "Linux"

- name: "Resolving pidproxy path"
  shell: "which pidproxy"
  register: pidproxy_output

- name: "Register supervisor_pidproxy_path fact"
  set_fact: supervisor_pidproxy_path="{{ pidproxy_output.stdout }}"

- name: "Creates {{ brew_install_path }}/etc/supervisor.d"
  file:
    path: "{{ brew_install_path }}/etc/supervisor.d"
    state: directory

- name: "Creates {{ brew_install_path }}/var/log/supervisor"
  file:
    path: "{{ brew_install_path }}/var/log/supervisor"
    state: directory

- name: Ensure supervisord.ini
  template:
    src: supervisord.ini.j2
    dest: '{{ brew_install_path }}/etc/supervisord.ini'

- name: "Absent {{ brew_install_path }}/etc/supervisord.conf"
  file:
    state: absent
    path: "{{ brew_install_path }}/etc/supervisord.conf"

- name: Ensure symlink for supervisord.ini
  file:
    src: "{{ brew_install_path }}/etc/supervisord.ini"
    dest: "{{ brew_install_path }}/etc/supervisord.conf"
    state: link

- name: Ensure permissions for supervisord socket
  ini_file:
    path: "{{ brew_install_path }}/etc/supervisord.ini"
    section: "unix_http_server"
    option: "chmod"
    value: "0770"

#- name: Ensure ownership for supervisord socket
#  ini_file:
#    path: "{{ brew_install_path }}/etc/supervisord.ini"
#    section: "unix_http_server"
#    option: "chown"
#    value: "root:{{ brew_group }}"

- name: "Ensure /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist"
  template:
    src: homebrew.mxcl.supervisor.plist.j2
    dest: '/Library/LaunchDaemons/homebrew.mxcl.supervisor.plist'
  become: yes
  when: ansible_system == "Darwin"

- name: "Ensure /lib/systemd/system/supervisord-devbrew.service"
  template:
    src: supervisord-devbrew.service.j2
    dest: /lib/systemd/system/supervisord-devbrew.service
    owner: root
    group: root
  when: ansible_system == "Linux"
  ignore_errors: yes
  become: yes

- name: "Ensure /usr/lib/systemd/system/supervisord-devbrew.service"
  template:
    src: supervisord-devbrew.service.j2
    dest: /usr/lib/systemd/system/supervisord-devbrew.service
    owner: root
    group: root
  when: ansible_system == "Linux"
  ignore_errors: yes
  become: yes

- name: "Ensure /etc/init.d/supervisord-devbrew"
  template:
    src: init-script.j2
    dest: /etc/init.d/supervisord-devbrew
    owner: root
    group: root
    mode: 0755
  when: ansible_system == "Linux"
  become: yes

- name: "Ensure supervisor-listener"
  template:
    src: supervisor-listener
    dest: '{{ brew_install_path }}/bin/supervisor-listener'
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    mode: 0755

- name: Postpone restart for supervisord-devbrew
  set_fact:
    service_started: "{{ service_started + [ 'supervisord-devbrew' ] }}"
