---

- name: "Installing nodejs"
  homebrew: 
    name: node 
    state: latest
#    install_options: "without-icu4c"

- name: "Setting fact"
  set_fact: 
    nodejs_installed: true

- name: "Installing yarn"
  homebrew:
    name: yarn
    state: latest

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
