---

- name: "Ensure nodejs"
  homebrew: 
    name: node 
    state: latest
#    install_options: "without-icu4c"

- name: "Setting fact"
  set_fact: 
    nodejs_installed: true

- name: "Ensure yarn"
  homebrew:
    name: yarn
    state: latest

- name: "Ensure nvm"
  homebrew:
    name: nvm
    state: latest

- name: "Updating rc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/{{item}}'
    marker: "# {mark} nvm"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "{{ brew_install_path }}/opt/nvm/nvm.sh" ] && . "{{ brew_install_path }}/opt/nvm/nvm.sh"  # This loads nvm
      [ -s "{{ brew_install_path }}/opt/nvm/etc/bash_completion.d/nvm" ] && . "{{ brew_install_path }}/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
  with_items: ['.zshrc', '.bashrc']
