---
- set_fact:
    default_php: "{{ php_versions[-1] }}"

- name: Looking for outdated configs
  find:
    paths: "{{ brew_install_path }}/etc/nginx/servers"
    patterns: "ph*.conf"
  register: old_php_nginx_config
  tags:
    - always

- name: Deleting of outdated config
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_php_nginx_config.files }}"
  tags:
    - always

- name: "Setting worker_connections to 256"
  lineinfile:
    path: '{{ brew_install_path }}/etc/nginx/nginx.conf'
    regexp: '.*worker_connections.+;'
    line: '    worker_connections 256;'
  tags:
    - always
    
- name: "Creates {{ brew_install_path }}/etc/nginx/dev.conf"
  template: 
    src: dev.conf.j2
    dest: "{{ brew_install_path }}/etc/nginx/dev.conf"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
  tags:
    - always

- name: "Creates {{ brew_install_path }}/etc/nginx/servers/{{item}}_{{root_domain}}.conf"
  template: 
    src: servers/php.conf.j2
    dest: "{{ brew_install_path }}/etc/nginx/servers/{{item}}_{{root_domain}}.conf"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
  with_items: "{{subdomains}}"
  tags:
    - always

- name: "Creates {{ brew_install_path }}/etc/nginx/custom_server.conf.tpl"
  template: 
    src: servers/custom_server.conf.tpl.j2
    dest: "{{ brew_install_path }}/etc/nginx/custom_server.conf.tpl"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
  tags:
    - always

- name: Cleanup installed nginx-error-pages
  file:
    path: "{{ brew_install_path }}/opt/nginx-error-pages"
    state: absent
  tags:
    - always

- name: Remove outdated files
  file:
    path: "{{ brew_install_path }}/etc/nginx/conf.d/default_server.conf"
    state: absent
  tags:
    - always

- name: Ensure nginx-error-pages
  git:
    repo: 'https://github.com/SergeyCherepanov/nginx-error-pages.git'
    dest: '{{ brew_install_path }}/opt/nginx-error-pages'
    version: 'master'
  tags:
    - always

- name: "Generate keys and signing for domains"
  shell: '{{ brew_install_path }}/bin/crtgen {{item}}.{{root_domain}}'
  with_items: "{{subdomains}}"
  tags:
    - always
