---
- name: "Ensure python@2"
  homebrew: 
    name: python@2
    state: latest

- name: "Resolve local python2 path"
  shell: "cd $(brew --prefix python@2)/bin; cd $(dirname $(realpath python2)); pwd"
  register: result

- name: "Register local_python2_path fact"
  set_fact: local_python2_path="{{ result.stdout }}"

- name: "Resolve local pip path"
  shell: "echo $(brew --prefix python@2)/bin/pip"
  register: result

- name: "Register local_pip2_path fact"
  set_fact: local_pip2_path="{{ result.stdout }}"

- debug:
    var: local_pip2_path
