---
- name: "Installing CoreUtils"
  homebrew: 
    name: coreutils
    state: latest

- name: "Adding coreutils to PATH in {{ brew_user_home_dir }}/.zshrc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/.zshrc'
    marker: "# {mark} coreutils PATH"
    create: yes
    block: |
      # export PATH="$({{ brew_brew_bin_path }}/brew --prefix coreutils)/libexec/gnubin:$PATH"

- name: "Adding coreutils to PATH in {{ brew_user_home_dir }}/.bashrc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/.bashrc'
    marker: "# {mark} coreutils PATH"
    create: yes
    block: |
      # export PATH="$({{ brew_brew_bin_path }}/brew --prefix coreutils)/libexec/gnubin:$PATH"
