---
brew_brew_bin_path: "{{ brew_install_path }}/bin"

brew_installed_packages:
  - ssh-copy-id
  - pv
  - htop
  - mc
  - wget
  - mtr
  - nmap
  - watch
  - hg
  - breezy
  - p7zip
  - autoconf
  - gomplate
  - gettext
  - glances
  - json-table
  - pup
  - fswatch
  - shellcheck
  - libmcrypt
  - yarn
  - yq
  - jq

brew_upgrade_all_packages: no

brew_taps:
  - homebrew/cask
  - digitalspacestdio/common
  - homebrew/cask-fonts 

brew_cask_apps: []

brew_cask_appdir: /Applications

brew_use_brewfile: true
brew_brewfile_dir: '~'
brew_directories:
  - '{{ brew_install_path }}/Caskroom'
  - '{{ brew_install_path }}/Cellar'
  - '{{ brew_install_path }}/Frameworks'
  - '{{ brew_install_path }}/Homebrew'
  - '{{ brew_install_path }}/bin'
  - '{{ brew_install_path }}/etc'
  - '{{ brew_install_path }}/include'
  - '{{ brew_install_path }}/lib'
  - '{{ brew_install_path }}/opt'
  - '{{ brew_install_path }}/sbin'
  - '{{ brew_install_path }}/share'
  - '{{ brew_install_path }}/var'
