---
- set_fact:
    default_php: "{{ php_versions[-1] }}"

- name: "Register mongo_bin_path fact"
  set_fact: mongo_bin_path="{{ mongodb_path }}/bin/mongo"

- name: Absent previous installed xhgui
  file:
    path: "{{ brew_install_path }}/opt/xhgui"
    state: absent

- name: "Starting mongodb"
  shell: "nohup {{ mongodb_path }}/bin/mongod --config {{ brew_install_path }}/etc/mongod.conf --logpath /tmp/mongodb.log > /dev/null &"
  args:
    chdir: /tmp

- name: "Waiting mongodb"
  shell: timeout 60s bash -c "until grep 'waiting for connections on port' /tmp/mongodb.log; do sleep 1; done"
  args:
    chdir: /tmp

- name: "Configure xhgui db"
  shell: >
    {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'meta.SERVER.REQUEST_TIME' : -1 } );" xhgui \
    && {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'profile.main().wt' : -1 } );" xhgui \
    && {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'profile.main().mu' : -1 } );" xhgui \
    && {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'profile.main().cpu' : -1 } );" xhgui \
    && {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'meta.url' : 1 } );" xhgui \
    && {{ mongo_bin_path }} --eval "db.results.ensureIndex( { 'meta.simple_url' : 1 } );" xhgui

- name: Ensure xhgui
  git:
    repo: "https://github.com/perftools/xhgui.git"
    dest: "{{ brew_install_path }}/opt/xhgui"
    version: "master"

- name: "Install xhgui"
  shell: >
    php {{ brew_install_path }}/bin/composer install
  args:
    chdir: "{{ brew_install_path }}/opt/xhgui"

- name: "Ensure {{ brew_install_path }}/etc/nginx/servers/xhgui.conf"
  template:
    src: nginx.xhgui.conf.j2
    dest: "{{ brew_install_path }}/etc/nginx/servers/xhgui.conf"

- name: "Ensure {{ brew_install_path }}/opt/xhgui/config/config.php"
  template:
    src: config.php.j2
    dest: "{{ brew_install_path }}/opt/xhgui/config/config.php"

- name: "Ensure xhgui.local in /etc/hosts"
  lineinfile:
    path: '/etc/hosts'
    line: '127.0.0.1    xhgui.local'
  become: yes

- name: "Stopping mongodb"
  shell: "pgrep mongod | xargs kill -15"
